version: '3.9'

services:
  php:
    image: docker-push.wynd.eu/php:8.1-fpm
    restart: always
    volumes:
      - sock:/var/run/php-fpm/
      - ./:/var/www/html
  nginx:
    image: docker-push.wynd.eu/nginx:1.22
    restart: always
    volumes:
      - sock:/var/run/php-fpm/
      - ./public:/var/www/html/public
    environment:
      UPSTREAM_SERVER: "unix:/var/run/php-fpm/php-fpm.sock"
    ports:
      - 8056:80

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  sock:
      driver: local

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
